export const POST_SHARE_START = 'POST_SHARE_START';
export const POST_SHARE_SUCCESS = 'POST_SHARE_SUCCESS';
export const POST_SHARE_FAILED = 'POST_SHARE_FAILED';
export const POST_IMAGE_UPLOAD_START = 'POST_IMAGE_UPLOAD_START';
export const POST_IMAGE_UPLOAD_SUCCESS = 'POST_IMAGE_UPLOAD_SUCCESS';
export const POST_IMAGE_UPLOAD_FAILED = 'POST_IMAGE_UPLOAD_FAILED';
