export const FOLLOW_START = 'FOLLOW_START';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAILED = 'FOLLOW_FAILED';

export const UNFOLLOW_START = 'UNFOLLOW_START';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_FAILED = 'FOLLOW_FAILED';
