export const GET_POST_TIMELINE_START = 'GET_POST_TIMELINE_START';
export const GET_POST_TIMELINE_SUCCESS = 'GET_POST_TIMELINE_SUCCESS';
export const GET_POST_TIMELINE_FAILED = 'GET_POST_TIMELINE_FAILED';

export const POST_LIKE_UNLIKE_START = 'POST_LIKE_UNLIKE_START';
export const POST_LIKE_UNLIKE_SUCCESS = 'POST_LIKE_UNLIKE_SUCCESS';
export const POST_LIKE_UNLIKE_FAILED = 'POST_LIKE_UNLIKE_FAILED';
