export const GET_POST_TIMELINE_START = 'GET_POST_TIMELINE_START';
export const GET_POST_TIMELINE_SUCCESS = 'GET_POST_TIMELINE_SUCCESS';
export const GET_POST_TIMELINE_FAILED = 'GET_POST_TIMELINE_FAILED';
