export const UPDATE_PROFILE_COVER_IMAGE_START =
  'UPDATE_PROFILE_COVER_IMAGE_START';
export const UPDATE_PROFILE_COVER_IMAGE_SUCCESS =
  'UPDATE_PROFILE_COVER_IMAGE_SUCCESS';
export const UPDATE_PROFILE_COVER_IMAGE_FAILED =
  'UPDATE_PROFILE_COVER_IMAGE_FAILED';

export const UPDATE_PROFILE_INFO_START = 'UPDATE_PROFILE_INFO_START';
export const UPDATE_PROFILE_INFO_SUCCESS = 'UPDATE_PROFILE_INFO_SUCCESS';
export const UPDATE_PROFILE_INFO_FAILED = 'UPDATE_PROFILE_INFO_FAILED';
